### ISSUE TITLE
1.8.3 causes rails app loading error.

### ISSUE THREAD

**Issue by garrettblehm** [tilo/smarter_csv#232]
This [PR](https://github.com/tilo/smarter_csv/pull/228) changed how smarter_csv is required and is causing some issues.

Here's the trace when trying to run `bin/rails console`. 

ruby: 3.2.1
smarter_csv: 1.8.3
```bash
gblehm@Garretts-Fleetio-M1-Macbook-Pro:Repos/my_project $ bundle show smarter_csv
/Users/gblehm/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/smarter_csv-1.8.3


gblehm@Garretts-Fleetio-M1-Macbook-Pro:Repos/my_project $ bin/rails console
rails aborted!
/Users/gblehm/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require': cannot load such file -- smarter_csv.bundle (LoadError)
        from /Users/gblehm/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
        from /Users/gblehm/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/smarter_csv-1.8.3/lib/smarter_csv.rb:7:in `<main>'
        from /Users/gblehm/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
        from /Users/gblehm/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
        from /Users/gblehm/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/bundler-2.3.25/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
        from /Users/gblehm/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/bundler-2.3.25/lib/bundler/runtime.rb:55:in `each'
        from /Users/gblehm/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/bundler-2.3.25/lib/bundler/runtime.rb:55:in `block in require'
        from /Users/gblehm/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/bundler-2.3.25/lib/bundler/runtime.rb:44:in `each'
        from /Users/gblehm/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/bundler-2.3.25/lib/bundler/runtime.rb:44:in `require'
        from /Users/gblehm/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/bundler-2.3.25/lib/bundler.rb:186:in `require'
        from /Users/gblehm/Repos/my_project/config/application.rb:18:in `<main>'
        from /Users/gblehm/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
        from /Users/gblehm/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
        from /Users/gblehm/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/railties-7.0.4.3/lib/rails/command/actions.rb:22:in `require_application!'
        from /Users/gblehm/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/railties-7.0.4.3/lib/rails/command/actions.rb:14:in `require_application_and_environment!'
        from /Users/gblehm/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/railties-7.0.4.3/lib/rails/commands/console/console_command.rb:101:in `perform'
        from /Users/gblehm/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
        from /Users/gblehm/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
        from /Users/gblehm/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
        from /Users/gblehm/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/railties-7.0.4.3/lib/rails/command/base.rb:87:in `perform'
        from /Users/gblehm/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/railties-7.0.4.3/lib/rails/command.rb:48:in `invoke'
        from /Users/gblehm/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/railties-7.0.4.3/lib/rails/commands.rb:18:in `<main>'
        from /Users/gblehm/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
        from /Users/gblehm/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
        from bin/rails:4:in `<main>'

**Comment by tilo** [comment]
@PhilCoggins @garrettblehm 1.8.4 will fix this
