### ISSUE TITLE
Incorrect line number for error

### ISSUE THREAD

**Issue by rex-remind101** [tilo/smarter_csv#285]
Actual
```
$ cat cats.csv
first name,last name,dogs,cats,birds,fish
     Dan,McAllister,2,1,2,4
     Lucy,Laweless "Lawless",,5,,
     Miles,O'Brian,,,,21
     Nancy,Homes,2,,1,

x = SmarterCSV.process('/Users/Rex/Documents/parentsquare/parent_square/cats.csv')
CSV::MalformedCSVError: Illegal quoting in line 1. [SmarterCSV: csv line 3]
from /Users/Me/.rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/gems/csv-3.3.0/lib/csv/parser.rb:1085:in `parse_quotable_robust'
Caused by CSV::MalformedCSVError: Illegal quoting in line 1.
from /Users/Me/.rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/gems/csv-3.3.0/lib/csv/parser.rb:1085:in `parse_quotable_robust'
```
Expected
`Caused by CSV::MalformedCSVError: Illegal quoting in line 2.` (assumes 0 counting)

**Comment by rex-remind101** [comment]
Looks like i was on an older version, though now i'm seeing different issues
